config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :admin do
    root to: 'banknotes#index'
    resources :banknotes
  end

  resources :withdrawals, only: %i(index create)
  root to: 'withdrawals#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banknote.rb
class Banknote < ApplicationRecord
  class << self
    def total
      all.inject(0) { |sum, nominal| sum + nominal.nominal * nominal.quantity }
    end

    def deduct(notes)
      grouped = notes.group_by { |a| a }.map { |k, v| [k, v.size] }.to_h
      grouped.each do |nominal, quantity|
        banknote = Banknote.find_by(nominal: nominal)
        banknote.quantity -= quantity
        banknote.save
      end
    end

    def to_h
      all.map { |a| [a.nominal, a.quantity] }.to_h
    end
  end
end

app/controllers/admin/banknotes_controller.rb
class Admin::BanknotesController < Admin::BaseController

  def index
    @banknotes = Banknote.all
  end

  def edit
    @banknote = Banknote.find(params[:id])
  end

  def update
    @banknote = Banknote.find(params[:id])
    if @banknote.update(banknote_params)
      redirect_to  admin_root_url, notice: 'Banknote was update'
    else
      render :edit, alert: 'Banknote was not update'
    end
  end

  private

  def banknote_params
    params.require(:banknote).permit(:name, :quantity)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :success, :danger, :info
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @banknotes = Banknote.all
    @money = 0
    Banknote.all.each do |banknote|
      @money += Banknote::NOMINAL[banknote.name] * banknote.quantity
    end
  end

  def withdrawal
    @money = Money.new(money_params)
    binding.pry
    if result = @money.withdraw(params['amount'].to_i)
      result.each do |nominal|
        banknote = Banknote.find_by(name: Banknote::NOMINAL.key(nominal))
        banknote.quantity -= 1
        banknote.save
      end
      flash[:success] = 'The operation was successful'
    else
      flash[:danger]  = 'Not enough money in the account'
    end

     redirect_to home_path
  end

  private

  def money_params
    result = Banknote.all.each_with_object({}) do |(banknote), memo|
      memo[Banknote::NOMINAL[banknote.name]] = banknote.quantity
    end    
  end
end

app/controllers/withdrawals_controller.rb
class WithdrawalsController < ApplicationController

  def index
    @banknotes = Banknote.all
  end

  def create
    money  = Money.new(Banknote.to_h)
    result = money.withdraw(withdrawal_params[:amount].to_i)

    if result.any?
      Banknote.deduct(result)
      flash[:success] = 'The operation was successful'
    else
      flash[:danger]  = 'Not enough money in the account'
    end
    redirect_to root_path
  end

  private

  def withdrawal_params
    params.require(:withdrawal).permit!
  end
end

app/helpers/admin/main_helper.rb
module Admin::MainHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banknotes_helper.rb
module BanknotesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/admin/banknotes/_form.html.erb
<%= form_for [:admin, @banknote] do |f| %>
  <%= f.text_field  :name %>
  <%= f.text_field :quantity %>
  <%= f.submit %>
<% end %>

app/views/admin/banknotes/edit.html.erb
<h1>Edit Banknotes</h1>

<%= render 'form' %>

app/views/admin/banknotes/index.html.erb
<div class="container">
  <h2>Banknotes</h2>  
  <%= link_to 'Add new banknote', new_admin_banknote_path, class: 'btn btn-success pull-right'%>          
  <table class="table">
    <thead>
      <tr>
        <th>title</th>
        <th>quantity</th>
      </tr>
    </thead>
    <tbody>
      <% @banknotes.each do |banknote| %>
        <tr>
          <td><%= banknote.name %></td>
          <td><%= banknote.quantity %></td>
          <td><%= link_to 'Edit', edit_admin_banknote_path(banknote)%>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</body>
</html>

app/views/admin/shared/_banknote_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="home_path">ATM</a>
    </div>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/admin/shared/_main_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="admin_root_path ">ATM</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/application/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %> ">
    <%= msg %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="container">
<h1>Bank</h1>
<h2><%= @money %></h2>
	<%= form_tag({controller: "home", action: "withdrawal"}, method: "post") do %>
	    <%= label_tag(:amount, "Сalculate for:") %>
	    <%= text_field_tag(:amount) %>
	    <%= submit_tag("withdrawal money") %>
	<% end %>
  <h2>Available banknotes</h2>         
  <table class="table">
    <thead>
      <tr>
        <th>title</th>
        <th>quantity</th>
      </tr>
    </thead>
    <tbody>
      <% @banknotes.each do |banknote| %>
        <tr>
          <td><%= banknote.name %></td>
          <td><%= banknote.quantity %></td>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</body>
</html>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'admin/shared/banknote_menu' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.content %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @story.content %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>

app/views/withdrawals/index.html.erb
<div class='container'>
  <h1>Bank</h1>
  <h2>Total: <%= Banknote.total %></h2>
  <div>
    <%= simple_form_for :withdrawal do |f| %>
      <%= f.input :amount %>
      <%= f.submit('Withdraw') %>
    <% end %>
  </div>

  <h2>Available banknotes</h2>         
  <table class="table">
    <thead>
      <tr>
        <th>title</th>
        <td>nominal</td>
        <th>quantity</th>

      </tr>
    </thead>
    <tbody>
      <% @banknotes.each do |banknote| %>
        <tr>
          <td><%= banknote.name %></td>
          <td><%= banknote.nominal %></td>
          <td><%= banknote.quantity %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>